name: Install Dependencies
run-name: Install Dependencies on Ubuntu ðŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    # based on https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    runs-on: ubuntu-22.04
    steps:
      - run: apt-get update
      - run: apt-get install python3.10
